### ISSUE TITLE
Unable to set value for is_monitoring_enabled

### ISSUE THREAD

**Issue by bz0qyz** [montastic/montastic-api-doc#1]
sending a PATCH request to an endpoint with 
{ "is_monitoring_enabled":  true }

does not enable or disable an endpoint as expected. Setting other parameters like "name" or "notes" works perfectly.

**Comment by supercobra** [comment]
Fixed. The `is_monitoring_enabled` has its own end point. We updated the documentation ([readme](https://github.com/montastic/montastic-api-doc)) and in the [Python example](https://github.com/montastic/montastic-api-doc/blob/master/examples/python/montastic-api-tests.py).
